language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t gwfernandez/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gwfernandez/docker-react npm run test
